In [54]:
import pandas as pd
import numpy as np
# from tqdm import tqdm
import random
import time
import csv
import json
import openai
import os
from tqdm import tqdm
import time
import ast

In [55]:
baseline_results = pd.read_csv("results/baseline_gpt_oss_1000.csv") #change name to baseline_gpt_oss_1000
baseline_results

   Argument ID                                             values    seconds
0       A01001  {'Be creative':0, 'Be curious':0, 'Have freedo...  30.924304
1       A01002  {'Be creative':1, 'Be curious':0, 'Have freedo...  25.552757
2       A01003  {'Be creative':0, 'Be curious':0, 'Have freedo...  32.587301
3       A01004  {'Be creative':0, 'Be curious':0, 'Have freedo...  21.698446
4       A01005  {'Be creative':0, 'Be curious':0, 'Have freedo...  35.828496
5       A01006  {'Be creative':0, 'Be curious':0, 'Have freedo...  33.169319
6       A01007  {'Be creative':0, 'Be curious':0, 'Have freedo...  29.317023
7       A01008  {'Be creative':0, 'Be curious':0, 'Have freedo...  28.456753
8       A01009  {'Be creative':0, 'Be curious':0, 'Have freedo...  36.537273
9       A01010  {'Be creative':0, 'Be curious':0, 'Have freedo...  39.077288
10      A01011  {"Be creative":0, "Be curious":0, "Have freedo...  22.374645
11      A01012  {'Be creative':0, 'Be curious':0, 'Have freedo...  25.795487
12      A01013  {'Be creative':0, 'Be curious':0, 'Have freedo...  31.276704
13      A01014  {'Be creative':0, 'Be curious':0, 'Have freedo...  31.062012
14      A01015  {'Be creative':0, 'Be curious':0, 'Have freedo...  31.741815
15      A01016  {'Be creative':0, 'Be curious':0, 'Have freedo...  26.081804
16      A01017  {'Be creative':0, 'Be curious':0, 'Have freedo...  21.583027
17      A01018  {'Be creative':0, 'Be curious':0, 'Have freedo...  23.769947
18      A01019  {'Be creative':0, 'Be curious':0, 'Have freedo...  52.047613
19      A01020  {'Be creative':1, 'Be curious':1, 'Have freedo...  30.840436
20      A02001  {\n'Be creative - allowing for more creativity...  42.976105
21      A02002  {'Be creative':0, 'Be curious':0, 'Have freedo...  26.426191
22      A02003  {'Be creative':0, 'Be curious':0, 'Have freedo...  31.277311
23      A02004  {'Be creative':0, 'Be curious':0, 'Have freedo...  21.603852
24      A02005  {'Be creative':0, 'Be curious':0, 'Have freedo...  23.601770
25      A02006  {'Be creative':1, 'Be curious':1, 'Have freedo...  26.313825
26      A02007  {'Be creative':0, 'Be curious':0, 'Have freedo...  24.312295
27      A02008  {'Be creative':0, 'Be curious':0, 'Have freedo...  26.785258
28      A02009  {'Be creative':0, 'Be curious':0, 'Have freedo...  24.395689
29      A02010  {'Be creative':0, 'Be curious':0, 'Have freedo...  30.840556
30      A02011  {'Be creative':0, 'Be curious':0, 'Have freedo...  21.554594
31      A02012  {'Be creative':0, 'Be curious':0, 'Have freedo...  13.246424
32      A02013  {'Be creative':0, 'Be curious':0, 'Have freedo...  26.424952
33      A02014  {'Be creative':0, 'Be curious':0, 'Have freedo...  25.978545
34      A02015  {'Be creative':0, 'Be curious':0, 'Have freedo...  23.082117
35      A02016  {'Be creative':0, 'Be curious':0, 'Have freedo...  20.112858
36      A02017  {'Be creative':0, 'Be curious':0, 'Have freedo...  25.975111
37      A02018  {'Be creative':1, 'Be curious':1, 'Have freedo...  27.041900
38      A02019  {'Be creative':0, 'Be curious':0, 'Have freedo...  27.678955
39      A02020  {'Be creative':0, 'Be curious':0, 'Have freedo...  24.781034
40      A03001  {'Be creative':0, 'Be curious':0, 'Have freedo...  26.912856
41      A03002  {'Be creative':0, 'Be curious':0, 'Have freedo...  30.907130
42      A03003  {'Be creative':0, 'Be curious':0, 'Have freedo...  27.794356
43      A03004  {'Be creative':0, 'Be curious':0, 'Have freedo...  28.955575
44      A03005  {'Be creative':0, 'Be curious':0, 'Have freedo...  39.058147
45      A03006  {'Be creative':0, 'Be curious':0, 'Have freedo...  23.744764
46      A03007  {'Be creative':0, 'Be curious':0, 'Have freedo...  25.910623
47      A03008  {'Be creative':0, 'Be curious':0, 'Have freedo...  31.243348
48      A03009  {'Be creative':0, 'Be curious':0, 'Have freedo...  30.724317
49      A03010  {'Be creative':0, 'Be curious':0, 'Have freedo...  26.363377
50      A03011  {'Be creative':0, 'Be curious':0, 'Have freedo...  34.551065
51      A03012  {'Be creative':1, 'Be curious':0, 'Have freedo...  31.692140
52      A03013  {'Be creative':1, 'Be curious':1, 'Have freedo...  46.911134

In [56]:
baseline_results['values'] = baseline_results['values'].apply(ast.literal_eval) # transformamos el output del LLM a un diccionario
baseline_results

   Argument ID                                             values    seconds
0       A01001  {'Be creative': 0, 'Be curious': 0, 'Have free...  30.924304
1       A01002  {'Be creative': 1, 'Be curious': 0, 'Have free...  25.552757
2       A01003  {'Be creative': 0, 'Be curious': 0, 'Have free...  32.587301
3       A01004  {'Be creative': 0, 'Be curious': 0, 'Have free...  21.698446
4       A01005  {'Be creative': 0, 'Be curious': 0, 'Have free...  35.828496
5       A01006  {'Be creative': 0, 'Be curious': 0, 'Have free...  33.169319
6       A01007  {'Be creative': 0, 'Be curious': 0, 'Have free...  29.317023
7       A01008  {'Be creative': 0, 'Be curious': 0, 'Have free...  28.456753
8       A01009  {'Be creative': 0, 'Be curious': 0, 'Have free...  36.537273
9       A01010  {'Be creative': 0, 'Be curious': 0, 'Have free...  39.077288
10      A01011  {'Be creative': 0, 'Be curious': 0, 'Have free...  22.374645
11      A01012  {'Be creative': 0, 'Be curious': 0, 'Have free...  25.795487
12      A01013  {'Be creative': 0, 'Be curious': 0, 'Have free...  31.276704
13      A01014  {'Be creative': 0, 'Be curious': 0, 'Have free...  31.062012
14      A01015  {'Be creative': 0, 'Be curious': 0, 'Have free...  31.741815
15      A01016  {'Be creative': 0, 'Be curious': 0, 'Have free...  26.081804
16      A01017  {'Be creative': 0, 'Be curious': 0, 'Have free...  21.583027
17      A01018  {'Be creative': 0, 'Be curious': 0, 'Have free...  23.769947
18      A01019  {'Be creative': 0, 'Be curious': 0, 'Have free...  52.047613
19      A01020  {'Be creative': 1, 'Be curious': 1, 'Have free...  30.840436
20      A02001  {'Be creative - allowing for more creativity o...  42.976105
21      A02002  {'Be creative': 0, 'Be curious': 0, 'Have free...  26.426191
22      A02003  {'Be creative': 0, 'Be curious': 0, 'Have free...  31.277311
23      A02004  {'Be creative': 0, 'Be curious': 0, 'Have free...  21.603852
24      A02005  {'Be creative': 0, 'Be curious': 0, 'Have free...  23.601770
25      A02006  {'Be creative': 1, 'Be curious': 1, 'Have free...  26.313825
26      A02007  {'Be creative': 0, 'Be curious': 0, 'Have free...  24.312295
27      A02008  {'Be creative': 0, 'Be curious': 0, 'Have free...  26.785258
28      A02009  {'Be creative': 0, 'Be curious': 0, 'Have free...  24.395689
29      A02010  {'Be creative': 0, 'Be curious': 0, 'Have free...  30.840556
30      A02011  {'Be creative': 0, 'Be curious': 0, 'Have free...  21.554594
31      A02012  {'Be creative': 0, 'Be curious': 0, 'Have free...  13.246424
32      A02013  {'Be creative': 0, 'Be curious': 0, 'Have free...  26.424952
33      A02014  {'Be creative': 0, 'Be curious': 0, 'Have free...  25.978545
34      A02015  {'Be creative': 0, 'Be curious': 0, 'Have free...  23.082117
35      A02016  {'Be creative': 0, 'Be curious': 0, 'Have free...  20.112858
36      A02017  {'Be creative': 0, 'Be curious': 0, 'Have free...  25.975111
37      A02018  {'Be creative': 1, 'Be curious': 1, 'Have free...  27.041900
38      A02019  {'Be creative': 0, 'Be curious': 0, 'Have free...  27.678955
39      A02020  {'Be creative': 0, 'Be curious': 0, 'Have free...  24.781034
40      A03001  {'Be creative': 0, 'Be curious': 0, 'Have free...  26.912856
41      A03002  {'Be creative': 0, 'Be curious': 0, 'Have free...  30.907130
42      A03003  {'Be creative': 0, 'Be curious': 0, 'Have free...  27.794356
43      A03004  {'Be creative': 0, 'Be curious': 0, 'Have free...  28.955575
44      A03005  {'Be creative': 0, 'Be curious': 0, 'Have free...  39.058147
45      A03006  {'Be creative': 0, 'Be curious': 0, 'Have free...  23.744764
46      A03007  {'Be creative': 0, 'Be curious': 0, 'Have free...  25.910623
47      A03008  {'Be creative': 0, 'Be curious': 0, 'Have free...  31.243348
48      A03009  {'Be creative': 0, 'Be curious': 0, 'Have free...  30.724317
49      A03010  {'Be creative': 0, 'Be curious': 0, 'Have free...  26.363377
50      A03011  {'Be creative': 0, 'Be curious': 0, 'Have free...  34.551065
51      A03012  {'Be creative': 1, 'Be curious': 0, 'Have free...  31.692140
52      A03013  {'Be creative': 1, 'Be curious': 1, 'Have free...  46.911134

#### Error Checking


Check if the predictions have been made correctly (dictionary with 54 keys and 54 values that are integers 0 / 1)

In [57]:
expected_keys_in_order = [
    'Be creative', 'Be curious', 'Have freedom of thought', 'Be choosing own goals',
    'Be independent', 'Have freedom of action', 'Have privacy', 'Have an exciting life',
    'Have a varied life', 'Be daring', 'Have pleasure', 'Be ambitious', 'Have success',
    'Be capable', 'Be intellectual', 'Be courageous', 'Have influence',
    'Have the right to command', 'Have wealth', 'Have social recognition',
    'Have a good reputation', 'Have a sense of belonging', 'Have good health',
    'Have no debts', 'Be neat and tidy', 'Have a comfortable life',
    'Have a safe country', 'Have a stable society', 'Be respecting traditions',
    'Be holding religious faith', 'Be compliant', 'Be self-disciplined',
    'Be behaving properly', 'Be polite', 'Be honoring elders', 'Be humble',
    'Have life accepted as is', 'Be helpful', 'Be honest', 'Be forgiving',
    'Have the own family secured', 'Be loving', 'Be responsible',
    'Have loyalty towards friends', 'Have equality', 'Be just',
    'Have a world at peace', 'Be protecting the environment',
    'Have harmony with nature', 'Have a world of beauty', 'Be broadminded',
    'Have the wisdom to accept others', 'Be logical', 'Have an objective view'
]

def is_valid(d):
    return (
        isinstance(d, dict)
        and len(d) == 54 # se han predicho 54 valores
        and list(d.keys()) == expected_keys_in_order # se cumple el orden y los nombres de los valores presentes en la lista original del prompt
        and all(isinstance(v, (int)) for v in d.values()) # es un número entero
        and all(v in (0, 1) for v in d.values()) # los valores son 0 o 1
    )

valid_mask = baseline_results["values"].apply(is_valid)

all_valid = valid_mask.all()

invalid_rows = baseline_results[~valid_mask]

# print all rows from the dataframe that do not follow the specified rules 
print(len(invalid_rows), "arguments have not been predicted according to the specified rules (54 keys), 54 values of 0/1)")

5 arguments have not been predicted according to the specified rules (54 keys), 54 values of 0/1)

In [58]:
invalid_rows

   Argument ID                                             values    seconds
5       A01006  {'Be creative': 0, 'Be curious': 0, 'Have free...  33.169319
9       A01010  {'Be creative': 0, 'Be curious': 0, 'Have free...  39.077288
16      A01017  {'Be creative': 0, 'Be curious': 0, 'Have free...  21.583027
20      A02001  {'Be creative - allowing for more creativity o...  42.976105
43      A03004  {'Be creative': 0, 'Be curious': 0, 'Have free...  28.955575

In [ ]:
I = 0
for bad_prediction in invalid_rows["values"]:
    print("\n\nInstancia mal clasificada:\n", bad_prediction)
    print(len(bad_prediction) == 54)
    print(list(bad_prediction.keys()) == expected_keys_in_order)
    print(all(isinstance(v, (int)) for v in bad_prediction.values())) # es un número entero
    print(all(v in (0, 1) for v in bad_prediction.values())) # los valores son 0 o 1

    dict_keys = set(bad_prediction.keys())
    expected_keys = set(expected_keys_in_order)

    missing = expected_keys - dict_keys
    extra = dict_keys - expected_keys

Instancia mal clasificada:
 {'Be creative': 0, 'Be curious': 0, 'Have freedom of thought': 0, 'Be choosing own goals': 0, 'Be independent': 0, 'Have freedom of action': 0, 'Have privacy': 0, 'Have an excited life': 0, 'Have a varied life': 0, 'Be daring': 0, 'Have pleasure': 0, 'Be ambitious': 0, 'Have success': 0, 'Be capable': 0, 'Be intellectual': 0, 'Be courageous': 1, 'Have influence': 1, 'Have the right to command': 0, 'Have wealth': 0, 'Have social recognition': 0, 'Have a good reputation': 0, 'Have a sense of belonging': 0, 'Have good health': 0, 'Have no debts': 0, 'Be neat and tidy': 0, 'Have a comfortable life': 0, 'Have a safe country': 0, 'Have a stable society': 1, 'Be respecting traditions': 0, 'Be holding religious faith': 0, 'Be compliant': 0, 'Be self-disciplined': 0, 'Be behaving properly': 0, 'Be polite': 0, 'Be honoring elders': 0, 'Be humble': 0, 'Have life accepted as is': 0, 'Be helpful': 0, 'Be honest': 0, 'Be forgiving': 0, 'Have the own family secured': 0, 'Be loving': 0, 'Be responsible': 1, 'Have loyalty towards friends': 0, 'Have equality': 0, 'Be just': 1, 'Have a world at peace': 0, 'Be protecting the environment': 0, 'Have harmony with nature': 0, 'Have a world of beauty': 0, 'Be broadminded': 0, 'Have the wisdom to accept others': 0, 'Be logical': 0, 'Have an objective view': 0}
True
False
True
True


Instancia mal clasificada:
 {'Be creative': 0, 'Be curious': 0, 'Have freedom of thought': 1, 'Be choosing own goals': 1, 'Be independent': 1, 'Have freedom of action': 1, 'Have privacy': 1, 'Have an exciting life': 0, 'Have a varied life': 0, 'Be daring': 0, 'Have pleasure': 0, 'Be ambitious': 0, 'Have success': 0, 'Be capable': 0, 'Be intellectual': 0, 'Be courageous': 0, 'Have influence': 0, 'Have the right to command': 0, 'Have wealth': 0, 'Have social recognition': 0, 'Have a good reputation': 0, 'Have sense of belonging': 1, 'Have good health': 0, 'Have no debts': 0, 'Be neat and tidy': 0, 'Have a comfortable life': 0, 'Have a safe country': 0, 'Have a stable society': 1, 'Be respecting traditions': 1, 'Be holding religious faith': 1, 'Be compliant': 1, 'Be self-disciplined': 0, 'Be behaving properly': 1, 'Be polite': 0, 'Be honoring elders': 0, 'Be humble': 0, 'Have life accepted as is': 0, 'Be helpful': 0, 'Be honest': 0, 'Be forgiving': 0, 'Have the own family secured': 0, 'Be loving': 0, 'Be responsible': 1, 'Have loyalty towards friends': 0, 'Have equality': 1, 'Be just': 1, 'Have a world at peace': 0, 'Be protecting the environment': 0, 'Have harmony with nature': 0, 'Have a world of beauty': 0, 'Be broadminded': 1, 'Have the wisdom to accept others': 1, 'Be logical': 1, 'Have an objective view': 1}
True
False
True
True


Instancia mal clasificada:
 {'Be creative': 0, 'Be curious': 0, 'Have freedom of thought': 1, 'Be choosing own goals': 1, 'Be independent': 1, 'Have freedom of action': 1, 'Have privacy': 0, 'Have an exciting life': 0, 'Have a varied life': 0, 'Be daring': 1, 'Have pleasure': 0, 'Be ambitious': 1, 'Have success': 1, 'Be capable': 1, 'Be intellectual': 1, 'Be courageous': 1, 'Have influence': 0, 'Have the right to command': 0, 'Have wealth': 0, 'Have social recognition': 0, 'Have a good reputation': 1, 'Have sense of belonging': 0, 'Have good health': 0, 'Have no debts': 0, 'Be neat and tidy': 0, 'Have comfortable life': 1, 'Have safe country': 0, 'Have stable society': 1, 'Be respecting traditions': 0, 'Be holding religious faith': 0, 'Be compliant': 0, 'Be self-disciplined': 0, 'Be behaving properly': 0, 'Be polite': 0, 'Be honoring elders': 0, 'Be humble': 0, 'Have life accepted as is': 1, 'Be helpful': 0, 'Be honest': 1, 'Be forgiving': 0, 'Have the own family secured': 0, 'Be loving': 0, 'Be responsible': 1, 'Have loyalty towards friends': 0, 'Have equality': 1, 'Be just': 1, 'Have a world at peace': 0, 'Be protecting the environment': 0, 'Have harmony with nature': 0, 'Have a world of beauty': 0, 'Be broadminded': 0, 'Have the wisdom to accept others': 1, 'Be logical': 1, 'Have an objective view': 1}
True
False
True
True


Instancia mal clasificada:
 {'Be creative - allowing for more creativity or imagination; being more creative; fostering creativity; promoting imagination': 0, 'Be curious - being the more interesting option; fostering curiosity; making people more keen to learn; promoting discoveries; sparking interest': 0, "Have freedom of thought - allowing people to figure things out on their own; allowing people to make up their mind; resulting in less censorship; resulting in less influence on people's thoughts": 0, 'Be choosing own goals - allowing people to choose what is best for them; allowing people to decide on their life; allowing people to follow their dreams': 0, 'Be independent - allowing people to plan on their own; resulting in fewer times people have to ask for consent': 1, 'Have freedom of action - allowing people to be self-determined; allowing people to do things even though this may hurt them in the long run; resulting in more times people can do what they want': 0, 'Have privacy - allowing for private spaces; allowing time alone; resulting in less surveillance; resulting in more control on what to disclose and to whom': 0, 'Have an exciting life - allowing people to experience foreign places; providing perspective-changing experiences; providing special activities': 0, 'Have a varied life - allowing people to change parts of their life; allowing people to move flat easily; promoting local clubs (sports, ...); providing many activities': 0, 'Be daring - allowing for risky actions; allowing to take risks; being more risky; fostering risk-taking': 0, 'Have pleasure - making life enjoyable; providing leisure; providing opportunities to have fun; providing sensuous gratification': 0, 'Be ambitious - allowing for ambitions; being more ambitious; fostering ambition; providing incentives for the difficult climb up the social ladder': 1, 'Have success - allowing people to be more successful; recognizing achievements': 1, 'Be capable - allowing to acquire competence in certain tasks; being more effective; resulting in a higher effectivity; showing competence in solving tasks': 1, 'Be intellectual - allowing to acquire high cognitive skills; being more reflective; resulting in more reflective behavior; showing intelligence': 0, 'Be courageous - being more courageous; fostering courage; making people stand up for their beliefs; promoting courage; showing courage': 0, 'Have influence - having more people to ask for a favor; resulting in more influence; resulting in more obligations towards the own side; resulting in more ways to control events': 0, 'Have the right to command - allowing experts to tell others what to do; allowing people to take command; fostering leadership; resulting in clearer hierarchies of command': 0, "Have wealth - allowing people to gain wealth and material possession; allowing to show one's wealth; allowing to use money for power; providing people with resources to control events; resulting in financial prosperity": 1, 'Have social recognition - allowing people to gain respect; avoiding humiliation; providing social recognition for actions': 0, "Have a good reputation - allowing people to build up their reputation; protecting one's public image; spreading reputation": 0, 'Have a sense of belonging - allowing people to establish groups; allowing people to join groups and show their group membership; allowing group members to show they care for each other; fostering a sense of belonging; resulting in fewer people forced to leave their groups': 0, 'Have good health - avoiding diseases; preserving health; having physiological and mental well-being; fostering activities to stay healthy; resulting in increased health': 1, 'Have no debts - avoiding indebtedness; having people always return a favor; reciprocating favors': 1, 'Be neat and tidy - allowing to clean up; being more clean or orderly; promoting cleanliness or neatness; resulting in higher cleanliness': 0, 'Have a comfortable life - providing subsistence income; resulting in having no financial worries; resulting in a higher general happiness; resulting in a prosperous life': 1, 'Have a safe country - caring for citizens; resulting in a state that can better act on crimes; resulting in a state that can better defend its citizens; resulting in a state that takes better care of its citizens; resulting in a stronger state': 1, 'Have a stable society - accepting or maintaining the existing social structure; preventing chaos and disorder; promoting the social order; resulting in a country that is more stable': 1, "Be respecting traditions - allowing to follow one's family's customs; honoring traditional practices; maintaining traditional values and ways of thinking; promoting the preservation of customs": 0, "Be holding religious faith - allowing to devote one's life to their faith; allowing the customs of a religion; being more adequate for a certain religion; promoting piety; spreading a religion": 0, "Be compliant - abiding to laws or rules; promoting to meet one's obligations; recognizing people who abide to laws or rules": 0, 'Be self-disciplined - fostering to exercise restraint; fostering to follow rules even when no-one is watching; fostering to set rules for oneself': 0, 'Be behaving properly - avoiding to violate informal rules or social conventions; fostering good manners; resulting in more people minding their manners': 0, 'Be polite - avoiding to upset other people; promoting to take others into account; resulting in being less annoying for others': 0, "Be honoring elders - fostering that children follow their parents; showing faith and respect towards one's elders": 0, 'Be humble - demoting arrogance; demoting to think one deserves more than other people; emphasizing the successful group over single persons; fostering to give back to society for the opportunities one got; fostering to not brag about what one achieved': 0, "Have life accepted as is - allowing people to accept their fate; fostering to submit to life's circumstances; promoting satisfaction with what one has; showing acceptance of one's own portion in life": 0, "Be helpful - allowing to help the people in one's group; being more helpful to those one cares for; fostering a readiness to help each other; promoting to work for the welfare of others in one group": 1, 'Be honest - being more honest; fostering honest ways of thinking; promoting honesty; recognizing people for their honesty; resulting in more honest social interaction': 0, 'Be forgiving - allowing people to forgive each other; giving people a second chance; being merciful; promoting a will to pardon others; providing paths to redemption': 0, "Have the own family secured - allowing people to protect their family; promoting to have a family; providing care for one's family": 1, "Be loving - allowing to place the well-being of others above the own well-being; allowing to show one's affection, compassion and sympathy; fostering close relationships; promoting self-respect and self-love as a means of care for oneself; promoting to concern oneself with the needs of dear ones": 0, 'Be responsible - allowing for clear responsibilities; fostering dependability; promoting reliability; resulting in more people being confident; taking responsibility': 1, 'Have loyalty towards friends - being a dependable and trustworthy friend; foster loyalty towards friends; promoting to give friends a full backing': 0, 'Have equality - fostering people of a lower social status; helping poorer regions of the world; providing all people with equal opportunities in life; resulting in a world were success is less determined by birth': 1, "Be just - allowing justice to be 'blind' to irrelevant aspects of a case; fostering a sense for justice; promoting fairness in competitions; protecting the weak and vulnerable in society; resulting a world were people are less discriminated based on race, gender, ...": 1, 'Have a world at peace - allowing for nations to cease fire; avoiding conflicts; fostering to see peace as fragile and precious; promoting to end wars; resulting in more people caring for all humanity': 0, 'Be protecting the environment - avoiding pollution; fostering to care for nature; promoting programs to restore nature; resulting in less damage to the ecosystem': 0, 'Have harmony with nature - allowing to avoid chemicals (especially in nutrition); allowing to avoid genetically modified organisms; fostering to treat animals or plants like them having souls; promoting a life in harmony with nature; resulting in more people reflecting the consequences of their actions towards the environment': 0, 'Have a world of beauty - allowing people to experience art; fostering to stand in awe of nature; promoting fine arts; promoting the beauty of nature; spreading beauty': 0, 'Be broadminded - allowing for discussion between groups; clearing up with prejudices; fostering to listen to and understand people who are different from oneself; promoting tolerance towards all kinds of people and groups; promoting to life within a different group for some time': 0, 'Have the wisdom to accept others - allowing people to accept disagreements; fostering to accept people even when one disagrees with them; promoting a mature understanding of different opinions; resulting in fewer partisans or fanatics': 0, 'Be logical - being better by the numbers but not by gut feeling; fostering a rational way of thinking; promoting focus and consistency; promoting the rational analysis of circumstances; promoting the scientific method': 1, 'Have an objective view - fostering to seek the truth; fostering to take on a neutral perspective; promoting to form an unbiased opinion; providing people with the means to make informed decisions; weighing all pros and cons': 1}
True
False
True
True


Instancia mal clasificada:
 {'Be creative': 0, 'Be curious': 0, 'Have freedom of thought': 0, 'Be choosing own goals': 0, 'Be independent': 0, 'Have freedom of action': 0, 'Have privacy': 0, 'Have an exciting life': 0, 'Have a varied life': 0, 'Be daring': 0, 'Have pleasure': 0, 'Be ambitious': 0, 'Have success': 0, 'Be capable': 0, 'Be intellectual': 0, 'Be courageous': 0, 'Have influence': 0, 'Have the right to command': 0, 'Have wealth': 0, 'Have social recognition': 0, 'Have a good reputation': 0, 'Have a sense of belonging': 0, 'Have good health': 0, 'Have no debts': 0, 'Be neat and tidy': 0, 'Have a comfortable life': 0, 'Have safe country': 1, 'Have stable society': 1, 'Be respecting traditions': 0, 'Be holding religious faith': 0, 'Be compliant': 1, 'Be self-disciplined': 0, 'Be behaving properly': 0, 'Be polite': 0, 'Be honoring elders': 0, 'Be humble': 0, 'Have life accepted as is': 0, 'Be helpful': 0, 'Be honest': 0, 'Be forgiving': 0, 'Have the own family secured': 0, 'Be loving': 0, 'Be responsible': 1, 'Have loyalty towards friends': 0, 'Have equality': 0, 'Be just': 1, 'Have a world at peace': 0, 'Be protecting the environment': 0, 'Have harmony with nature': 0, 'Have a world of beauty': 0, 'Be broadminded': 0, 'Have the wisdom to accept others': 0, 'Be logical': 0, 'Have an objective view': 0}
True
False
True
True

### Errors

Your dictionary contains:

'Have an excited life'

But the expected list contains:

'Have an exciting life'


------------------------------

Your dictionary contains:

'Have sense of belonging'

Expected list contains:

'Have a sense of belonging'

--------------------------------